spring.application.name=stripe.payment
stripe.secretKey=sk_test_51QThM5CH4iCvkNBNsIfLYbeGAJxrFjIFm9rn0RPrZLsJWLeGoEBK34T5ZjjG2wl7yDb2H2TbdHDksqLPlJ4i64Z400vayKm6CB
stripe.publishableKey=pk_test_51QThM5CH4iCvkNBNVk9hvVjvvpqN7xv3fvCdDVrgRttk4ZchYf85Q61Lg1byRyhhvl2yA3j3se1gyrKnvhk7rrY200MljuEIq5
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http=DEBUG
spring.web.resources.add-mappings=false